CREATE TABLE `NewsletterGenerator` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`projectId` text,
	`name` text NOT NULL,
	`topics` text,
	`targetAudience` text NOT NULL,
	`tone` text DEFAULT 'professional' NOT NULL,
	`competitorEmails` text,
	`includeEmailInsights` integer DEFAULT true NOT NULL,
	`maxSections` integer DEFAULT 5 NOT NULL,
	`schedule` text DEFAULT 'manual' NOT NULL,
	`scheduleDay` integer,
	`scheduleTime` text,
	`status` text DEFAULT 'active' NOT NULL,
	`lastRunAt` integer,
	`lastRunStatus` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON UPDATE no action ON DELETE no action
);
