"use client";

import { AlertCircle, FileText, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { useContentReview } from "@/hooks/use-content-review";
import { ContentFiltersBar } from "./content-filters";
import { ContentReviewCard } from "./content-review-card";
import { ContentStatusBadge } from "./content-status-badge";

interface ContentReviewTabProps {
	projectId?: string;
}

export function ContentReviewTab({ projectId }: ContentReviewTabProps) {
	const {
		items,
		stats,
		loading,
		error,
		filters,
		setFilters,
		approveContent,
		rejectContent,
		clearError,
		refresh,
	} = useContentReview(projectId);

	if (loading) {
		return (
			<div className="flex items-center justify-center py-12">
				<Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
				<span className="ml-2 text-muted-foreground">
					Loading content...
				</span>
			</div>
		);
	}

	const pendingCount = stats.byStatus?.pending_review || 0;
	const approvedCount = stats.byStatus?.approved || 0;
	const publishedCount = stats.byStatus?.published || 0;
	const failedCount = stats.byStatus?.failed || 0;

	return (
		<div className="space-y-6">
			{/* Error banner */}
			{error && (
				<div className="rounded-lg border border-red-200 bg-red-50 p-3 dark:border-red-800 dark:bg-red-950">
					<div className="flex items-center gap-2">
						<AlertCircle className="h-4 w-4 text-red-500" />
						<span className="flex-1 text-sm text-red-700 dark:text-red-300">
							{error}
						</span>
						<Button
							onClick={clearError}
							variant="ghost"
							size="sm"
							className="h-6 text-xs"
						>
							Dismiss
						</Button>
					</div>
				</div>
			)}

			{/* Header */}
			<div className="flex items-center justify-between">
				<div>
					<h2 className="text-lg font-semibold">Content Review</h2>
					<p className="text-sm text-muted-foreground">
						Review and approve content generated by robots
					</p>
				</div>
				<Button
					onClick={refresh}
					variant="outline"
					size="sm"
					className="h-8"
				>
					<RefreshCw className="h-3.5 w-3.5 mr-1" />
					Refresh
				</Button>
			</div>

			{/* Stats cards */}
			<div className="grid grid-cols-4 gap-3">
				<Card className="p-3 text-center">
					<div className="text-2xl font-bold text-amber-600">
						{pendingCount}
					</div>
					<div className="text-xs text-muted-foreground">Pending</div>
				</Card>
				<Card className="p-3 text-center">
					<div className="text-2xl font-bold text-green-600">
						{approvedCount}
					</div>
					<div className="text-xs text-muted-foreground">Approved</div>
				</Card>
				<Card className="p-3 text-center">
					<div className="text-2xl font-bold text-emerald-600">
						{publishedCount}
					</div>
					<div className="text-xs text-muted-foreground">Published</div>
				</Card>
				<Card className="p-3 text-center">
					<div className="text-2xl font-bold text-red-600">
						{failedCount}
					</div>
					<div className="text-xs text-muted-foreground">Failed</div>
				</Card>
			</div>

			{/* Filters */}
			<ContentFiltersBar filters={filters} onFiltersChange={setFilters} />

			{/* Content grid */}
			{items.length === 0 ? (
				<Card className="p-8 text-center">
					<FileText className="mx-auto h-10 w-10 text-muted-foreground/50" />
					<h3 className="mt-3 text-sm font-medium">No content found</h3>
					<p className="mt-1 text-sm text-muted-foreground">
						{filters.status || filters.contentType || filters.sourceRobot
							? "Try adjusting your filters"
							: "Content will appear here when robots generate it"}
					</p>
				</Card>
			) : (
				<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
					{items.map((item) => (
						<ContentReviewCard
							key={item.id}
							item={item}
							onApprove={approveContent}
							onReject={rejectContent}
							onRefresh={refresh}
						/>
					))}
				</div>
			)}
		</div>
	);
}
